controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(img`
        ........................
        .....ffff...............
        ...fff22fff.............
        ..fff2222fff............
        .fffeeeeeefff...........
        .ffe222222eef...........
        .fe2ffffff2ef...........
        .ffffeeeeffff...........
        ffefbf44fbfeff..........
        fee41fddf14eef..........
        .ffffdddddeef...........
        fddddf444eef............
        fbbbbf2222f4e...........
        fbbbbf2222fd4...........
        .fccf45544f44...........
        ..ffffffff..............
        ....ff..ff..............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `, mySprite, 0, -50)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    otherSprite.destroy(effects.bubbles, 500)
    scene.cameraShake(4, 500)
    info.changeLifeBy(-1)
})
let Space_Junk: Sprite = null
let projectile: Sprite = null
let mySprite: Sprite = null
effects.starField.startScreenEffect()
mySprite = sprites.create(img`
    . . . . . . . c d . . . . . . . 
    . . . . . . . c d . . . . . . . 
    . . . . . . . c d . . . . . . . 
    . . . . . . . c b . . . . . . . 
    . . . . . . . f f . . . . . . . 
    . . . . . . . c 6 . . . . . . . 
    . . . . . . . f f . . . . . . . 
    . . . . . . . 8 6 . . . . . . . 
    . . . . . . 8 8 9 8 . . . . . . 
    . . . . . . 8 6 9 8 . . . . . . 
    . . . . . c c c 8 8 8 . . . . . 
    . . . . 8 8 6 6 6 9 8 8 . . . . 
    . . 8 f f f c c e e f f 8 8 . . 
    . 8 8 8 8 8 8 6 6 6 6 9 6 8 8 . 
    8 8 8 8 8 8 8 8 6 6 6 9 6 6 8 8 
    8 8 8 8 8 8 8 8 6 6 6 6 9 6 8 8 
    `, SpriteKind.Player)
game.onUpdateInterval(500, function () {
    Space_Junk = sprites.createProjectileFromSide(img`
        ...ffffff..........ccc..
        ...ff22ccff.......c44f..
        ....fffccccfff...c442f..
        ....cc24442222ccc4422f..
        ...c99b222222222cc22fc..
        ..c999111b222222222222c.
        .c2bb11199222ccccccc222f
        c22222222222c222cccfffff
        f22222222222442222ccc...
        .f222222222224442222c...
        ..ff2222222cffc44222c...
        ....fffffffcffffcccc....
        .........f2c2ffff.......
        .........fcc2ffff.......
        ..........ffffff........
        ........................
        `, 0, 50)
    Space_Junk.x = randint(0, scene.screenWidth())
    Space_Junk.setKind(SpriteKind.Enemy)
})
